// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	schedule "go-skeleton-code/pkg/schedule"

	mock "github.com/stretchr/testify/mock"
)

// JobHandler is an autogenerated mock type for the JobHandler type
type JobHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *JobHandler) Execute(_a0 context.Context, _a1 schedule.Schedule) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, schedule.Schedule) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJobHandler creates a new instance of JobHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobHandler {
	mock := &JobHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
